-- MySQL Script generated by MySQL Workbench
-- Mon Jan  2 20:11:31 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering




-- -----------------------------------------------------
-- Table `stockquotedata_basic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stockquotedata_basic` ;

CREATE TABLE IF NOT EXISTS `stockquotedata_basic` (
  `stockquotedatabasic_id` INT NOT NULL AUTO_INCREMENT,
  `isin` CHAR(12) NOT NULL,
  `stockname` VARCHAR(100) NULL,
  `stockindex` VARCHAR(10) NULL,
  `symbol` VARCHAR(7) NULL,
  `financial_year` DATE NULL,
  PRIMARY KEY (`stockquotedatabasic_id`),
  INDEX `isin_idx` (`isin` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stockquotedata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stockquotedata` ;

CREATE TABLE IF NOT EXISTS `stockquotedata` (
  `stockquotedata_id` INT NOT NULL AUTO_INCREMENT,
  `stockquotedatabasic_id` INT NOT NULL,
  `fetch_date` DATE NOT NULL,
  `return_on_equity` DECIMAL(5,2) NULL,
  `ebit_margin` DECIMAL(5,2) NULL,
  `equity_ration` DECIMAL(5,2) NULL,
  `analysts_count` SMALLINT UNSIGNED NULL,
  `analysts_opinion` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`stockquotedata_id`),
  INDEX `stockquotedatabasic_fk_idx` (`stockquotedatabasic_id` ASC),
  CONSTRAINT `stockquotedatabasic_fk`
    FOREIGN KEY (`stockquotedatabasic_id`)
    REFERENCES `stockquotedata_basic` (`stockquotedatabasic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `historical_quotes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `historical_quotes` ;

CREATE TABLE IF NOT EXISTS `historical_quotes` (
  `historical_quotes_id` INT NOT NULL AUTO_INCREMENT,
  `stockquotedata_id` INT NOT NULL,
  `quote_date` DATE NOT NULL,
  `quote` DECIMAL(5,2) NULL,
  PRIMARY KEY (`historical_quotes_id`),
  INDEX `hq_stockquotedata_fk_idx` (`stockquotedata_id` ASC),
  CONSTRAINT `hq_stockquotedata_fk`
    FOREIGN KEY (`stockquotedata_id`)
    REFERENCES `stockquotedata` (`stockquotedata_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `price_earnings_ratio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `price_earnings_ratio` ;

CREATE TABLE IF NOT EXISTS `price_earnings_ratio` (
  `price_earnings_ratio_id` INT NOT NULL AUTO_INCREMENT,
  `stockquotedata_id` INT NOT NULL,
  `per_year` YEAR NULL,
  `per_value` DECIMAL(5,2) NULL,
  `estimated` TINYINT(1) NULL,
  PRIMARY KEY (`price_earnings_ratio_id`),
  INDEX `per_stockquotedata_fk_idx` (`stockquotedata_id` ASC),
  CONSTRAINT `per_stockquotedata_fk`
    FOREIGN KEY (`stockquotedata_id`)
    REFERENCES `stockquotedata` (`stockquotedata_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eps` ;

CREATE TABLE IF NOT EXISTS `eps` (
  `eps_id` INT NOT NULL AUTO_INCREMENT,
  `stockquotedata_id` INT NOT NULL,
  `per_year` YEAR NULL,
  `per_value` DECIMAL(5,2) NULL,
  `estimated` TINYINT(1) NULL,
  PRIMARY KEY (`eps_id`),
  INDEX `eps_stockquotedata_fk_idx` (`stockquotedata_id` ASC),
  CONSTRAINT `eps_stockquotedata_fk`
    FOREIGN KEY (`stockquotedata_id`)
    REFERENCES `stockquotedata` (`stockquotedata_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
